# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 13:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
                ('documentation', models.FileField(blank=True, upload_to='documentation', verbose_name='Documentation')),
                ('mounting_type', models.IntegerField(choices=[(1, 'Surface mounting'), (2, 'Pin assembly'), (3, 'Other')], default=3, verbose_name='Mounting type')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.IntegerField(choices=[(1, 'Resistor'), (2, 'Capacitor'), (3, 'Inductivity'), (11, 'Diode'), (12, 'Suppressor'), (13, 'Zener diode'), (15, 'Transistor'), (17, 'Chip'), (23, 'Blank board'), (24, 'Board'), (25, 'Device'), (26, 'Other')], default=26, verbose_name='Type')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('value', models.CharField(default='', max_length=20, verbose_name='Value')),
                ('documentation', models.FileField(blank=True, upload_to='documentation', verbose_name='Documentation')),
                ('short_characteristic', models.TextField(blank=True, verbose_name='Short Characteristic')),
                ('template', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Template')),
                ('analogue', models.ManyToManyField(blank=True, related_name='_component_analogue_+', to='components.Component', verbose_name='Analogue')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.Case', verbose_name='Case')),
            ],
        ),
    ]
