# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='Postcode')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('site', models.URLField(blank=True, unique=True, verbose_name='Internet address')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=43, verbose_name='Surname')),
                ('position', models.CharField(blank=True, max_length=30, verbose_name='Position')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('description', models.TextField(blank=True, verbose_name='Additional information')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier', verbose_name='Employer')),
            ],
        ),
    ]
