# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercontact',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.Phone', verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.Phone', verbose_name='Phone number'),
        ),
    ]
