# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 13:54
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Expecting'), (2, 'Assembling'), (3, 'Testing'), (4, 'In storage'), (5, 'Wrote off')], default=1, verbose_name='Status')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Price')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date of modifying')),
                ('serial_number', models.IntegerField(blank=True, unique=True, verbose_name='Serial number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component', verbose_name='Component')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Status', verbose_name='Status')),
            ],
        ),
    ]
